### ISSUE TITLE
Vimeo video ID for episode 6 is the id for episode 10

### ISSUE THREAD

**Issue by sheriffderek** [robconery/nuxt-walkthrough#3]

**Comment by sheriffderek** [comment]
![CleanShot 2023-06-13 at 09 28 35@2x](https://github.com/robconery/nuxt-walkthrough/assets/2066617/7c2d4764-15c1-47e1-bb09-7ee267c9c67f)

**Comment by robconery** [comment]
Yeah things got a little confusing recording the walkthrough and then realizing I needed to add some intro stuff... so the numbers got out of whack. Sigh. I fixed this at app.bigmachine.io and will send out an update in the next few days.

**Comment by aenfield** [comment]
On app.bigmachine.io the video for 'Menus, Data-driven UI, Styling' is still the incorrect Pinia video. The text below the video is I think correct, but not the video itself. 

Here's what I see:
<img width="869" alt="Screenshot 2023-06-19 154011" src="https://github.com/robconery/nuxt-walkthrough/assets/1650563/9ed11a1e-bcb8-4c54-82bb-78cd38342a0b">

**Comment by robconery** [comment]
Oh good grief. I... don't know why that got so borked. I *hope* it's fixed now.
